import { PlaceholderPage } from '@/components/ui/PlaceholderPage';

export default function ErrorReportsPage() {
  return (
    <PlaceholderPage
      title="Error Reports"
      description="Review application error reports submitted by users or generated by the platform."
      behaviors={[
        'List error reports with type, affected user (anonymised), and timestamp',
        'Filter by error type: crash, network, auth, payment, map',
        'Filter by status: open, investigating, resolved, dismissed',
        'View error details — no personal data in error payloads',
        'Assign severity: low, medium, high, critical',
        'Mark as investigating — creates audit log entry',
        'Resolve with resolution notes — creates audit log entry',
        'Dismiss false positives — creates audit log entry',
        'Paginated — never load all error reports at once',
        'Do not expose device identifiers, exact location, or push tokens in error details',
        'TODO: Connect UI to backend error report endpoint',
        'TODO: Add severity and status filter controls',
      ]}
    />
  );
}
