package com.kungsbackacarcommunity.app.auth

import android.annotation.SuppressLint
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * [GoogleIdTokenProvider] backed by the Credential Manager API
 * (docs/auth-mobile-requirements.md — Android Google Sign-In).
 *
 * The OAuth web client id comes from the `default_web_client_id` resource,
 * generated by the google-services Gradle plugin from google-services.json.
 * That file is intentionally not committed, so the lookup is a guarded
 * runtime check: without it sign-in reports unavailable instead of crashing.
 */
class GoogleCredentialTokenProvider(
    private val activityContext: Context,
) : GoogleIdTokenProvider {

    override suspend fun fetchGoogleIdToken(): String {
        val serverClientId =
            resolveServerClientId(activityContext)
                ?: throw SignInUnavailableException(
                    "Google Sign-In is not configured for this build (missing google-services.json).",
                )

        val googleIdOption =
            GetGoogleIdOption.Builder()
                .setServerClientId(serverClientId)
                .setFilterByAuthorizedAccounts(false)
                .build()
        val request = GetCredentialRequest.Builder().addCredentialOption(googleIdOption).build()

        val result =
            try {
                CredentialManager.create(activityContext)
                    .getCredential(activityContext, request)
            } catch (exception: GetCredentialException) {
                // Never log tokens or credential contents.
                throw SignInFailedException("Google credential flow did not complete.", exception)
            }

        val credential = result.credential
        if (
            credential is CustomCredential &&
            credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            return GoogleIdTokenCredential.createFrom(credential.data).idToken
        }
        throw SignInFailedException("Unexpected credential type: ${credential.type}")
    }

    companion object {
        private const val WEB_CLIENT_ID_RESOURCE = "default_web_client_id"

        /**
         * Runtime lookup by name is required because the resource only exists
         * when the google-services plugin is applied — compile-time R access
         * would break the credential-less CI build.
         */
        @SuppressLint("DiscouragedApi")
        fun resolveServerClientId(context: Context): String? {
            val resId =
                context.resources.getIdentifier(
                    WEB_CLIENT_ID_RESOURCE,
                    "string",
                    context.packageName,
                )
            if (resId == 0) return null
            return context.getString(resId).takeIf { it.isNotBlank() }
        }
    }
}
