package com.kungsbackacarcommunity.app.auth

import android.annotation.SuppressLint
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * [GoogleIdTokenProvider] backed by the Credential Manager API
 * (docs/auth-mobile-requirements.md — Android Google Sign-In).
 *
 * The OAuth web client id comes from the `default_web_client_id` resource,
 * generated by the google-services Gradle plugin from google-services.json.
 * That file is intentionally not committed, so the lookup is a guarded
 * runtime check: without it sign-in reports unavailable instead of crashing.
 */
class GoogleCredentialTokenProvider(
    private val activityContext: Context,
) : GoogleIdTokenProvider {

    override suspend fun fetchGoogleIdToken(): String {
        val serverClientId =
            resolveServerClientId(activityContext)
                ?: throw SignInUnavailableException(
                    "Google Sign-In is not configured for this build (missing google-services.json).",
                )

        val googleIdOption =
            GetGoogleIdOption.Builder()
                .setServerClientId(serverClientId)
                .setFilterByAuthorizedAccounts(false)
                .build()
        val request = GetCredentialRequest.Builder().addCredentialOption(googleIdOption).build()

        val result =
            try {
                CredentialManager.create(activityContext)
                    .getCredential(activityContext, request)
            } catch (exception: GetCredentialException) {
                throw toSignInException(exception)
            }

        val credential = result.credential
        if (
            credential is CustomCredential &&
            credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            return GoogleIdTokenCredential.createFrom(credential.data).idToken
        }
        throw SignInFailedException("Unexpected credential type: ${credential.type}")
    }

    companion object {
        private const val WEB_CLIENT_ID_RESOURCE = "default_web_client_id"

        /**
         * Maps a Credential Manager failure onto the app's sign-in exception
         * vocabulary. This is where a USER CANCELLATION is separated from a real
         * fault, and it is the whole fix for issue #457.
         *
         * A pre-auth sign-in report auto-files a PUBLIC GitHub issue
         * (functions/src/diagnostics/signInIssues-core.ts). So the line drawn here
         * is the one the other two reporting pipelines in this repo already draw:
         * the live-share reporter does not auto-file `NotMember`, and the friends
         * reporter excludes business-rule refusals, because filing those "would
         * report the app working correctly" (see ClientErrorReporting.kt — "Only
         * report genuine FAULTS"). A user who opens the sheet and presses back is
         * the app working correctly.
         *
         * Dropped (never reported), because each is an EXPECTED outcome the user
         * can either live with or fix themselves:
         * - [GetCredentialCancellationException] -> [SignInCancelledException]:
         *   the user dismissed the sheet.
         * - [NoCredentialException] -> [SignInNoGoogleAccountException]: there is
         *   no Google account on the device. The sign-in screen now tells the user
         *   exactly that and offers a route to the add-account screen, so this is
         *   an actionable prerequisite rather than a fault. (When #457 was fixed
         *   this one was kept reportable ON PURPOSE, because back then it was a
         *   dead end the user could do nothing about; making it actionable is what
         *   changes the answer.)
         *
         * Everything else stays a reported [SignInFailedException], deliberately:
         * a provider misconfiguration, an unsupported device or an interrupted
         * flow are all things an admin needs to see. Do NOT widen this branch
         * without the same reasoning — over-filtering silently blinds the
         * diagnostics pipeline, which is a worse failure mode than a little noise.
         * The test for "may I drop this?" is whether the USER has a concrete next
         * step; if they don't, keep the visibility.
         *
         * Never logs tokens or credential contents. The stable androidx error
         * TYPE (e.g. `androidx.credentials.TYPE_NO_CREDENTIAL`) rides along as the
         * PII-safe diagnostic code; the concrete subtype is preserved via `cause`.
         */
        internal fun toSignInException(exception: GetCredentialException): Exception =
            when (exception) {
                is GetCredentialCancellationException ->
                    SignInCancelledException("User dismissed the Google credential sheet.")

                is NoCredentialException ->
                    SignInNoGoogleAccountException("No Google account on this device.")

                else ->
                    SignInFailedException(
                        "Google credential flow did not complete.",
                        exception,
                        diagnosticCode = exception.type,
                    )
            }

        /**
         * Runtime lookup by name is required because the resource only exists
         * when the google-services plugin is applied — compile-time R access
         * would break the credential-less CI build.
         */
        @SuppressLint("DiscouragedApi")
        fun resolveServerClientId(context: Context): String? {
            val resId =
                context.resources.getIdentifier(
                    WEB_CLIENT_ID_RESOURCE,
                    "string",
                    context.packageName,
                )
            if (resId == 0) return null
            return context.getString(resId).takeIf { it.isNotBlank() }
        }
    }
}
