import SwiftUI

/// The member's own Crown-Hunt claim history — a read of their `crownHuntClaims`
/// (owner-only). A net-new iOS surface with no Android counterpart (the Android
/// hub does not list claim history), built on the shared contract shape.
///
/// A dumb switch over ``CrownHuntClaimsUiState``; every decision lives in the
/// pure ``CrownHuntClaimsCoordinator``. Nil coordinator = config-less build →
/// the unavailable placeholder.
///
/// LOCALIZATION: the per-row OUTCOME reuses the existing `crownHunt.result*`
/// vocabulary and awarded points reuse `crownHunt.kpValue`, but this surface's
/// own chrome (screen title + empty prompt) has no key in the localization
/// contract yet — those two keys (`crownHunt.claimHistoryTitle`,
/// `crownHunt.claimHistoryEmpty`) are FLAGGED for the contract owner to add to
/// contracts/localization/{sv,en}.json (regenerated by the strings generator —
/// the catalog is never hand-edited). Until then a `defaultValue` keeps the
/// screen readable.
struct ClaimHistoryScreen: View {
    let coordinator: CrownHuntClaimsCoordinator?

    var body: some View {
        ScrollView {
            // A LazyVStack, not a VStack: the list is bounded to
            // ``CrownHuntClaims/queryLimit`` (100) rows, and a plain VStack
            // would eagerly lay every row out even when the member has never
            // scrolled past the first few.
            LazyVStack(spacing: KccSpacing.s3) {
                content
            }
            .padding(KccSpacing.s4)
        }
        .navigationTitle(Text(verbatim: Self.title))
        .task { coordinator?.start() }
    }

    /// Screen title — the flagged `crownHunt.claimHistoryTitle` key with a
    /// default until it lands in the contract (the string-literal `defaultValue`
    /// initializer both localizes and provides the interim fallback). Internal
    /// so ``CrownHuntHubView`` can reuse it as the toolbar entry point's
    /// accessibility label without duplicating the fallback string.
    static var title: String {
        String(localized: "crownHunt.claimHistoryTitle", defaultValue: "Claim history")
    }

    private static var emptyBody: String {
        String(
            localized: "crownHunt.claimHistoryEmpty",
            defaultValue: "You have not collected any crowns yet."
        )
    }

    @ViewBuilder
    private var content: some View {
        if let coordinator {
            switch coordinator.state {
            case .loading:
                CrownHuntMessageState(title: "crownHunt.screenTitle", message: "crownHunt.loading")
            case .empty:
                VStack(spacing: KccSpacing.s3) {
                    Text(verbatim: Self.title)
                        .font(.headline)
                    Text(verbatim: Self.emptyBody)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
                .frame(maxWidth: .infinity)
                .padding(KccSpacing.s6)
            case .loaded(let claims):
                ForEach(claims) { claim in
                    ClaimRow(claim: claim)
                }
            case .unavailable:
                CrownHuntMessageState(
                    title: "crownHunt.screenTitle", message: "crownHunt.resultFeatureDisabled"
                )
            case .failed:
                CrownHuntMessageState(
                    title: "crownHunt.screenTitle",
                    message: "crownHunt.statsError",
                    retry: { coordinator.reload() }
                )
            }
        } else {
            CrownHuntMessageState(
                title: "crownHunt.screenTitle", message: "crownHunt.resultFeatureDisabled"
            )
        }
    }
}

/// One claim attempt: its localized outcome, when it happened, and — for an
/// awarded claim — the Crown Points earned.
private struct ClaimRow: View {
    let claim: CrownHuntClaim

    var body: some View {
        CrownHuntCard {
            HStack(alignment: .firstTextBaseline) {
                Text(CrownHuntStrings.resultKey(claim.result))
                    .font(.subheadline)
                    .fontWeight(.semibold)
                    .foregroundStyle(claim.result == .awarded ? KccPalette.successGreen : Color.primary)
                Spacer()
                if claim.result == .awarded, let points = claim.pointsAwarded {
                    Text(CrownHuntStrings.kpValue(points))
                        .font(.subheadline)
                        .fontWeight(.semibold)
                }
            }
            if let claimedAt = claim.claimedAt {
                Text(claimedAt.formatted(date: .abbreviated, time: .shortened))
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
        }
    }
}

#Preview("Claims – loaded") {
    NavigationStack {
        ScrollView {
            VStack(spacing: KccSpacing.s3) {
                ClaimRow(
                    claim: CrownHuntClaim(
                        id: "1", pointId: "p1", result: .awarded,
                        claimedAt: Date(), pointsAwarded: 25
                    )
                )
                ClaimRow(
                    claim: CrownHuntClaim(
                        id: "2", pointId: "p2", result: .movingTooFast,
                        claimedAt: Date(), pointsAwarded: nil
                    )
                )
            }
            .padding()
        }
    }
}
